# Type: Object, Required: Yes
#
# General server settings.
settings:

  # Type: String, Required: No, Default: ./screens
  #
  # The path to the directory where the screen images are
  # rendered to and served from.
  #
  # The file path is resolved relative to the location of
  # configuration file.
  #
  # The directory doesn't need to exist, it is created by
  # the server if it does not exist.
  screenImagePath: screens

  # Type: String, Required: No, Default: https://trmnl.app/api
  #
  # The base URI for the TRMNL API where the server will
  # fetch the latest firmware information.
  #
  # You shouldn't need to change this.
  trmnlApiUri: https://trmnl.app/api

  # Type: Array, Required: Yes
  #
  # A collection of API keys that will grant access to the
  # admin API.
  adminApiKeys:
    - "Q7F3G2N8W9KJ4RT1B6ZP0XHD5C2VYMA"

# Type: Object, Required: Yes
#
# Collection of devices that the server will manage.
devices:

  - # Type: String, Required: Yes
    #
    # The friendly ID for the device.
    id: test-device

    # Type: String, Required: Yes
    #
    # The MAC address for the device.
    address: 8A:3F:CD:91:7B:E4

    # Type: String, Required: Yes
    #
    # The API key for the device to use in order to
    # authenticate with the server.
    #
    # This needs to have a minimum length of 16 characters.
    key: 9KJ7T2QZP1H4V8MW3RCD0XY6BNA5FGU

    # Type: Boolean, Required: No, Default: true
    #
    # Indicates whether the device should be sent firmware
    # updates by the server when available.
    autoUpdate: true

    # Type: String, Required: No, Default: 1
    #
    # Indicates the bit depth that the device supports,
    # this also implies the number of colors that the
    # screen images will contain.
    bitDepth: 2

    # Type: Array, Required: Yes
    #
    # The collection of screens for the device that
    # will be cycled through.
    screens:

      - # Type: String, Required: Yes
        #
        # The layout indicating how the panels will be
        # organized on screen. The available layouts are:
        #  - P1Full
        #  - P2L1xR1
        #  - P2T1xB1
        #  - P3L1xR2
        #  - P3L2xR1
        #  - P4Grid
        #
        # The PX prefix states the exact number of panels
        # that the layout supports.
        layout: P2L1xR1

        # Type: Array, Required: Yes
        #
        # The collection of panels to render on the screen.
        panels:

          # This is an example of a `join-wifi` panel.
          - name: join-wifi
            settings:

              # Type: String, Required: Yes
              #
              # The SSID of the WiFi network being joined.
              ssid: ssid

              # Type: String, Required: Yes
              #
              # The passowrd for the WiFi network being
              # joined.
              password: password

              # Type: String, Required: Yes
              #
              # The encryption type used by the WiFi
              # network, this can be `WPA` or `WEP`.
              encryption: WPA

              # Type: Boolean, Required: No, Default: false
              #
              # Indicates if the WiFi network is hidden or
              # not.
              hidden: false

              # Type: String, Required: No
              #
              # A message to render under the WiFi QR code.
              message: Join our Guest WiFi network

          # This is an example of a `tfl-issues` panel.
          - name: tube-status
            settings:

              # Type: Array, Required: No
              #
              # A collection of no more than 8 TFL lines to
              # prioritize the status of when they are facing
              # disruption.
              #
              # The following lines are accepted:
              #   - bakerloo
              #   - central
              #   - circle
              #   - district
              #   - hammersmith-city
              #   - jubilee
              #   - metropolitan
              #   - northern
              #   - piccadilly
              #   - victoria
              #   - waterloo-city
              #   - liberty
              #   - lioness
              #   - mildmay
              #   - suffragette
              #   - weaver
              #   - windrush
              #   - elizabeth
              #   - dlr
              prioritizing:
                - piccadilly
                - dlr
                - elizabeth
